variables:
  DOCKER_IMAGE_NAME: docker.io/vishalwankhad/nws_demo
  DOCKER_TAG: ${CI_COMMIT_SHORT_SHA}
  DOCKER_REGISTRY_URL_AUTH: https://index.docker.io/v1/

# Define the stages
stages:
- build
- test
- deploy

# Define the jobs
build-with-dind:
  image: docker:24.0.5
  services: 
  - docker:24.0.5-dind
  stage: build
  script: 
    - echo "${DOCKER_HUB_TOKEN}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin
    - docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_TAG} .
    - docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_TOKEN}
    - docker push ${DOCKER_IMAGE_NAME}:${DOCKER_TAG} 

build-with-kaniko:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - echo "${CI_PROJECT_DIR}"
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${DOCKER_REGISTRY_URL_AUTH}\":{\"auth\":\"$(echo -n ${DOCKER_HUB_USERNAME}:${DOCKER_HUB_TOKEN} | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${DOCKER_IMAGE_NAME}:${DOCKER_TAG}"